### PR TITLE
Update of CI infrastructure

### PR DESCRIPTION
**Pull request by dalonsoa**
Updates the CI infrastructure, most notably the python versions GUIKIT is tested and the versions of the actions.

### CODE REVIEW

**Comment by dalonsoa** [comment]
@alexdewar , after this is merged, I'll release a new version.

**Review by alexdewar — APPROVED** [review]
LGTM!

Is Python 3.11 safe to use now....?

**Comment by dalonsoa** [comment]
It is the current stable version and all tests pass with it (except in MacOS, which is excluded). So, it should become the standard version. And we should consider deprecating 3.7 soon.

**Comment by alexdewar** [comment]
Interesting. I haven't tried anything with 3.11 yet but I hear it's much faster than 3.10...

**Pull request merged**
